# Generated by Django 3.1.4 on 2021-05-16 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='posts',
        ),
    ]
